version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloudretail
    ports:
      - '5432:5432'
